call git clone https://github.com/mvaganov/NonStandard.git
call git clone https://github.com/mvaganov/NonStandardLines.git
call git clone https://github.com/mvaganov/NonStandardScripting.git
call git clone https://github.com/mvaganov/NonStandardUnityUtility.git
call git clone https://github.com/mvaganov/NonStandardMouseCursorIcons.git
call git clone https://github.com/mvaganov/NonStandardInput.git
call git clone https://github.com/mvaganov/NonStandardCharacter.git
call git clone https://github.com/mvaganov/NonStandardUI.git
call git clone https://github.com/mvaganov/NonStandardSystem.git
call git clone https://github.com/mvaganov/NonStandardParticles.git
call git clone https://github.com/mvaganov/NonStandardDataSheet.git
call git clone https://github.com/mvaganov/NonStandardGameUi.git
call git clone https://github.com/mvaganov/NonStandardCmd.git
call git clone https://github.com/mvaganov/NonStandardStory.git
