'use strict';

const fs = require('fs');

let rawdata = fs.readFileSync('ls.json');
let listing = JSON.parse(rawdata);

for (const [key, value] of Object.entries(listing)) {
	if (value.listed === false) { continue; }
	//console.log(`${key}: ${value}`);
	let folderName = GetFolderName(value);
	let packageFolder = `../${folderName}`
	let packagePath = packageFolder + '/package.json';
	let packageText = CreatePackageFileData(value,listing);
	fs.writeFile(packagePath, packageText, err => {
		if (err) { console.error(err); return; }
		console.log("wrote "+packagePath);
	});
}

// line escape converter, so strings can be passed into other string input
function lnesc(text) { return text.replace(/\n/g, "\\n").replace(/\"/g, "\\\"").replace(/\'/g, "\\\'").replace(/\t/g, "\\t"); }

function GetFolderName(packageData) { 
	let fullname = packageData.url;
	let indexSlash = fullname.lastIndexOf("/");
	let indexDot = fullname.lastIndexOf(".git");
	return fullname.substring(indexSlash+1, indexDot);
}

function CreatePackageFileData(packageData, listing) {
	const infoHeader = "NonStandard library imported using NonStandard package management";
	let name = packageData.name;
	let id = packageData.id;
	let desc = packageData.desc ? infoHeader + "\n\n" + packageData.desc : infoHeader;
	let dependencies = [];
	if (packageData.req) {
		for (const [key,value] of Object.entries(packageData.req)) {
			let dep = listing[value];
			if (!dep) {
				console.log(`missing dependency '${value}'`);
				continue;
			}
			dependencies.push(dep);
		}
	}
	let dependenciesVersionString = (dependencies.length > 0 ? "{\n" : "{}");
	dependencies.forEach((d, i) => {
		dependenciesVersionString += `\t\t\"${d.id}\": \"${d.v}\"`;
		if (i < dependencies.length-1) {
			dependenciesVersionString += '",\n';
		} else {
			dependenciesVersionString += '"\n\t}';
		}
	});
	let author = "Michael Vaganov";
	let email = "mvaganov@gmail.com";
	let authorurl = "https://github.com/mvaganov/NonStandard";
	let version = packageData.v ? packageData.v : "1.0.0";
	let keywords = packageData.keywords ? packageData.keywords : ["library", "NonStandard"];
	let keywordsString = `[\n		"${keywords.join('",\n		"')}"\n	]`;
	var packageTemplate =
`{
	"@comment package": ["autogenerated by the update.js script in NonStandard"],
	"name": "${id}",
	"version": "${version}",
	"displayName": "${name}",
	"description": "${lnesc(desc)}.",
	"unity": "2019.4",
	"dependencies": ${dependenciesVersionString},
	"keywords": ${keywordsString},
	"author": {
		"name": "${author}",
		"email": "${email}",
		"url": "${authorurl}"
	},
	"type": "library"
}`;
	return packageTemplate;
}
